name: hw1_env
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy==1.20.3
    - pandas==1.3.3
    - seaborn
    - matplotlib
    - scikit-learn==1.0.1
    - torch==1.10.0
    - lightgbm==3.2.1
    - scipy==1.7.1